/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_objectweb_proactive_compi_control_ProActiveMPIComm_MessageRecvHandler */

#ifndef _Included_org_objectweb_proactive_compi_control_ProActiveMPIComm_MessageRecvHandler
#define _Included_org_objectweb_proactive_compi_control_ProActiveMPIComm_MessageRecvHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
