
package com.amazonaws.ec2.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvailabilityZone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailabilityZone">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ZoneName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ZoneState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailabilityZone", propOrder = {
    "zoneName",
    "zoneState"
})
public class AvailabilityZone {

    @XmlElement(name = "ZoneName", required = true)
    protected String zoneName;
    @XmlElement(name = "ZoneState", required = true)
    protected String zoneState;

    /**
     * Default constructor
     * 
     */
    public AvailabilityZone() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public AvailabilityZone(final String zoneName, final String zoneState) {
        this.zoneName = zoneName;
        this.zoneState = zoneState;
    }

    /**
     * Gets the value of the zoneName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneName() {
        return zoneName;
    }

    /**
     * Sets the value of the zoneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneName(String value) {
        this.zoneName = value;
    }

    public boolean isSetZoneName() {
        return (this.zoneName!= null);
    }

    /**
     * Gets the value of the zoneState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneState() {
        return zoneState;
    }

    /**
     * Sets the value of the zoneState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneState(String value) {
        this.zoneState = value;
    }

    public boolean isSetZoneState() {
        return (this.zoneState!= null);
    }

    /**
     * Sets the value of the ZoneName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public AvailabilityZone withZoneName(String value) {
        setZoneName(value);
        return this;
    }

    /**
     * Sets the value of the ZoneState property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public AvailabilityZone withZoneState(String value) {
        setZoneState(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetZoneName()) {
            xml.append("<ZoneName>");
            xml.append(escapeXML(getZoneName()));
            xml.append("</ZoneName>");
        }
        if (isSetZoneState()) {
            xml.append("<ZoneState>");
            xml.append(escapeXML(getZoneState()));
            xml.append("</ZoneState>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetZoneName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("ZoneName"));
            json.append(" : ");
            json.append(quoteJSON(getZoneName()));
            first = false;
        }
        if (isSetZoneState()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("ZoneState"));
            json.append(" : ");
            json.append(quoteJSON(getZoneState()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
