package com.amazonaws.ec2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Volume" type="{http://ec2.amazonaws.com/doc/2008-05-05/}Volume" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "volume" })
@XmlRootElement(name = "DescribeVolumesResult")
public class DescribeVolumesResult {

    @XmlElement(name = "Volume", required = true)
    protected List<Volume> volume;

    /**
     * Default constructor
     * 
     */
    public DescribeVolumesResult() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public DescribeVolumesResult(final List<Volume> volume) {
        this.volume = volume;
    }

    /**
     * Gets the value of the volume property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the volume property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVolume().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Volume }
     * 
     * 
     */
    public List<Volume> getVolume() {
        if (volume == null) {
            volume = new ArrayList<Volume>();
        }
        return this.volume;
    }

    public boolean isSetVolume() {
        return ((this.volume != null) && (!this.volume.isEmpty()));
    }

    public void unsetVolume() {
        this.volume = null;
    }

    /**
     * Sets the value of the Volume property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public DescribeVolumesResult withVolume(Volume... values) {
        for (Volume value : values) {
            getVolume().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param volume
     *     allowed object is
     *     {@link Volume }
     *     
     */
    public void setVolume(List<Volume> volume) {
        this.volume = volume;
    }

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        java.util.List<Volume> volumeList = getVolume();
        for (Volume volume : volumeList) {
            xml.append("<Volume>");
            xml.append(volume.toXMLFragment());
            xml.append("</Volume>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '&':
                    sb.append("&amp;");
                    break;
                case '<':
                    sb.append("&lt;");
                    break;
                case '>':
                    sb.append("&gt;");
                    break;
                case '\'':
                    sb.append("&#039;");
                    break;
                case '"':
                    sb.append("&quot;");
                    break;
                default:
                    sb.append(c);
            }
        }
        return sb.toString();
    }

    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetVolume()) {
            if (!first)
                json.append(", ");
            json.append("\"Volume\" : [");
            java.util.List<Volume> volumeList = getVolume();
            for (Volume volume : volumeList) {
                if (volumeList.indexOf(volume) > 0)
                    json.append(", ");
                json.append("{");
                json.append("");
                json.append(volume.toJSONFragment());
                json.append("}");
                first = false;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '/':
                    sb.append("\\/");
                    break;
                case '\b':
                    sb.append("\\b");
                    break;
                case '\f':
                    sb.append("\\f");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < ' ') {
                        sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                    } else {
                        sb.append(c);
                    }
            }
        }
        sb.append("\"");
        return sb.toString();
    }

}
