package com.amazonaws.ec2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImageId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Owner" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExecutableBy" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "imageId", "owner", "executableBy" })
@XmlRootElement(name = "DescribeImagesRequest")
public class DescribeImagesRequest {

    @XmlElement(name = "ImageId")
    protected List<String> imageId;
    @XmlElement(name = "Owner")
    protected List<String> owner;
    @XmlElement(name = "ExecutableBy")
    protected List<String> executableBy;

    /**
     * Default constructor
     * 
     */
    public DescribeImagesRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public DescribeImagesRequest(final List<String> imageId, final List<String> owner,
            final List<String> executableBy) {
        this.imageId = imageId;
        this.owner = owner;
        this.executableBy = executableBy;
    }

    /**
     * Gets the value of the imageId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getImageId() {
        if (imageId == null) {
            imageId = new ArrayList<String>();
        }
        return this.imageId;
    }

    public boolean isSetImageId() {
        return ((this.imageId != null) && (!this.imageId.isEmpty()));
    }

    public void unsetImageId() {
        this.imageId = null;
    }

    /**
     * Gets the value of the owner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the owner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOwner() {
        if (owner == null) {
            owner = new ArrayList<String>();
        }
        return this.owner;
    }

    public boolean isSetOwner() {
        return ((this.owner != null) && (!this.owner.isEmpty()));
    }

    public void unsetOwner() {
        this.owner = null;
    }

    /**
     * Gets the value of the executableBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the executableBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExecutableBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExecutableBy() {
        if (executableBy == null) {
            executableBy = new ArrayList<String>();
        }
        return this.executableBy;
    }

    public boolean isSetExecutableBy() {
        return ((this.executableBy != null) && (!this.executableBy.isEmpty()));
    }

    public void unsetExecutableBy() {
        this.executableBy = null;
    }

    /**
     * Sets the value of the ImageId property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public DescribeImagesRequest withImageId(String... values) {
        for (String value : values) {
            getImageId().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the Owner property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public DescribeImagesRequest withOwner(String... values) {
        for (String value : values) {
            getOwner().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the ExecutableBy property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public DescribeImagesRequest withExecutableBy(String... values) {
        for (String value : values) {
            getExecutableBy().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the imageId property.
     * 
     * @param imageId
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageId(List<String> imageId) {
        this.imageId = imageId;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param owner
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(List<String> owner) {
        this.owner = owner;
    }

    /**
     * Sets the value of the executableBy property.
     * 
     * @param executableBy
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutableBy(List<String> executableBy) {
        this.executableBy = executableBy;
    }

    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetImageId()) {
            if (!first)
                json.append(", ");
            json.append("\"ImageId\" : [");
            java.util.List<String> imageIdList = getImageId();
            for (String imageId : imageIdList) {
                if (imageIdList.indexOf(imageId) > 0)
                    json.append(", ");
                json.append(quoteJSON(imageId));
            }
            json.append("]");
            first = false;
        }
        if (isSetOwner()) {
            if (!first)
                json.append(", ");
            json.append("\"Owner\" : [");
            java.util.List<String> ownerList = getOwner();
            for (String owner : ownerList) {
                if (ownerList.indexOf(owner) > 0)
                    json.append(", ");
                json.append(quoteJSON(owner));
            }
            json.append("]");
            first = false;
        }
        if (isSetExecutableBy()) {
            if (!first)
                json.append(", ");
            json.append("\"ExecutableBy\" : [");
            java.util.List<String> executableByList = getExecutableBy();
            for (String executableBy : executableByList) {
                if (executableByList.indexOf(executableBy) > 0)
                    json.append(", ");
                json.append(quoteJSON(executableBy));
            }
            json.append("]");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '/':
                    sb.append("\\/");
                    break;
                case '\b':
                    sb.append("\\b");
                    break;
                case '\f':
                    sb.append("\\f");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < ' ') {
                        sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                    } else {
                        sb.append(c);
                    }
            }
        }
        sb.append("\"");
        return sb.toString();
    }

}
