
package com.amazonaws.ec2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SecurityGroup" type="{http://ec2.amazonaws.com/doc/2008-05-05/}SecurityGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "securityGroup"
})
@XmlRootElement(name = "DescribeSecurityGroupsResult")
public class DescribeSecurityGroupsResult {

    @XmlElement(name = "SecurityGroup", required = true)
    protected List<SecurityGroup> securityGroup;

    /**
     * Default constructor
     * 
     */
    public DescribeSecurityGroupsResult() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public DescribeSecurityGroupsResult(final List<SecurityGroup> securityGroup) {
        this.securityGroup = securityGroup;
    }

    /**
     * Gets the value of the securityGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurityGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecurityGroup }
     * 
     * 
     */
    public List<SecurityGroup> getSecurityGroup() {
        if (securityGroup == null) {
            securityGroup = new ArrayList<SecurityGroup>();
        }
        return this.securityGroup;
    }

    public boolean isSetSecurityGroup() {
        return ((this.securityGroup!= null)&&(!this.securityGroup.isEmpty()));
    }

    public void unsetSecurityGroup() {
        this.securityGroup = null;
    }

    /**
     * Sets the value of the SecurityGroup property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public DescribeSecurityGroupsResult withSecurityGroup(SecurityGroup... values) {
        for (SecurityGroup value: values) {
            getSecurityGroup().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the securityGroup property.
     * 
     * @param securityGroup
     *     allowed object is
     *     {@link SecurityGroup }
     *     
     */
    public void setSecurityGroup(List<SecurityGroup> securityGroup) {
        this.securityGroup = securityGroup;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        java.util.List<SecurityGroup> securityGroupList = getSecurityGroup();
        for (SecurityGroup securityGroup : securityGroupList) {
            xml.append("<SecurityGroup>");
            xml.append(securityGroup.toXMLFragment());
            xml.append("</SecurityGroup>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetSecurityGroup()) {
            if (!first) json.append(", ");
            json.append("\"SecurityGroup\" : [");
            java.util.List<SecurityGroup> securityGroupList = getSecurityGroup();
            for (SecurityGroup securityGroup : securityGroupList) {
                if (securityGroupList.indexOf(securityGroup) > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(securityGroup.toJSONFragment());
                json.append("}");
                first = false;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
