package com.amazonaws.ec2.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsoleOutput" type="{http://ec2.amazonaws.com/doc/2008-05-05/}ConsoleOutput"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "consoleOutput" })
@XmlRootElement(name = "GetConsoleOutputResult")
public class GetConsoleOutputResult {

    @XmlElement(name = "ConsoleOutput", required = true)
    protected ConsoleOutput consoleOutput;

    /**
     * Default constructor
     * 
     */
    public GetConsoleOutputResult() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public GetConsoleOutputResult(final ConsoleOutput consoleOutput) {
        this.consoleOutput = consoleOutput;
    }

    /**
     * Gets the value of the consoleOutput property.
     * 
     * @return
     *     possible object is
     *     {@link ConsoleOutput }
     *     
     */
    public ConsoleOutput getConsoleOutput() {
        return consoleOutput;
    }

    /**
     * Sets the value of the consoleOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsoleOutput }
     *     
     */
    public void setConsoleOutput(ConsoleOutput value) {
        this.consoleOutput = value;
    }

    public boolean isSetConsoleOutput() {
        return (this.consoleOutput != null);
    }

    /**
     * Sets the value of the ConsoleOutput property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public GetConsoleOutputResult withConsoleOutput(ConsoleOutput value) {
        setConsoleOutput(value);
        return this;
    }

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetConsoleOutput()) {
            ConsoleOutput consoleOutput = getConsoleOutput();
            xml.append("<ConsoleOutput>");
            xml.append(consoleOutput.toXMLFragment());
            xml.append("</ConsoleOutput>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '&':
                    sb.append("&amp;");
                    break;
                case '<':
                    sb.append("&lt;");
                    break;
                case '>':
                    sb.append("&gt;");
                    break;
                case '\'':
                    sb.append("&#039;");
                    break;
                case '"':
                    sb.append("&quot;");
                    break;
                default:
                    sb.append(c);
            }
        }
        return sb.toString();
    }

    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetConsoleOutput()) {
            if (!first)
                json.append(", ");
            json.append("\"ConsoleOutput\" : {");
            ConsoleOutput consoleOutput = getConsoleOutput();

            json.append(consoleOutput.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '/':
                    sb.append("\\/");
                    break;
                case '\b':
                    sb.append("\\b");
                    break;
                case '\f':
                    sb.append("\\f");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < ' ') {
                        sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                    } else {
                        sb.append(c);
                    }
            }
        }
        sb.append("\"");
        return sb.toString();
    }

}
