
package com.amazonaws.ec2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageAttribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageAttribute">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LaunchPermission" type="{http://ec2.amazonaws.com/doc/2008-05-05/}LaunchPermission" minOccurs="0"/>
 *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="KernelId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RamdiskId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BlockDeviceMapping" type="{http://ec2.amazonaws.com/doc/2008-05-05/}BlockDeviceMapping" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageAttribute", propOrder = {
    "imageId",
    "launchPermission",
    "productCode",
    "kernelId",
    "ramdiskId",
    "blockDeviceMapping"
})
public class ImageAttribute {

    @XmlElement(name = "ImageId", required = true)
    protected String imageId;
    @XmlElement(name = "LaunchPermission")
    protected LaunchPermission launchPermission;
    @XmlElement(name = "ProductCode", required = true)
    protected List<String> productCode;
    @XmlElement(name = "KernelId")
    protected String kernelId;
    @XmlElement(name = "RamdiskId")
    protected String ramdiskId;
    @XmlElement(name = "BlockDeviceMapping")
    protected BlockDeviceMapping blockDeviceMapping;

    /**
     * Default constructor
     * 
     */
    public ImageAttribute() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public ImageAttribute(final String imageId, final LaunchPermission launchPermission, final List<String> productCode, final String kernelId, final String ramdiskId, final BlockDeviceMapping blockDeviceMapping) {
        this.imageId = imageId;
        this.launchPermission = launchPermission;
        this.productCode = productCode;
        this.kernelId = kernelId;
        this.ramdiskId = ramdiskId;
        this.blockDeviceMapping = blockDeviceMapping;
    }

    /**
     * Gets the value of the imageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * Sets the value of the imageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageId(String value) {
        this.imageId = value;
    }

    public boolean isSetImageId() {
        return (this.imageId!= null);
    }

    /**
     * Gets the value of the launchPermission property.
     * 
     * @return
     *     possible object is
     *     {@link LaunchPermission }
     *     
     */
    public LaunchPermission getLaunchPermission() {
        return launchPermission;
    }

    /**
     * Sets the value of the launchPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaunchPermission }
     *     
     */
    public void setLaunchPermission(LaunchPermission value) {
        this.launchPermission = value;
    }

    public boolean isSetLaunchPermission() {
        return (this.launchPermission!= null);
    }

    /**
     * Gets the value of the productCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProductCode() {
        if (productCode == null) {
            productCode = new ArrayList<String>();
        }
        return this.productCode;
    }

    public boolean isSetProductCode() {
        return ((this.productCode!= null)&&(!this.productCode.isEmpty()));
    }

    public void unsetProductCode() {
        this.productCode = null;
    }

    /**
     * Gets the value of the kernelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKernelId() {
        return kernelId;
    }

    /**
     * Sets the value of the kernelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKernelId(String value) {
        this.kernelId = value;
    }

    public boolean isSetKernelId() {
        return (this.kernelId!= null);
    }

    /**
     * Gets the value of the ramdiskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRamdiskId() {
        return ramdiskId;
    }

    /**
     * Sets the value of the ramdiskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRamdiskId(String value) {
        this.ramdiskId = value;
    }

    public boolean isSetRamdiskId() {
        return (this.ramdiskId!= null);
    }

    /**
     * Gets the value of the blockDeviceMapping property.
     * 
     * @return
     *     possible object is
     *     {@link BlockDeviceMapping }
     *     
     */
    public BlockDeviceMapping getBlockDeviceMapping() {
        return blockDeviceMapping;
    }

    /**
     * Sets the value of the blockDeviceMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlockDeviceMapping }
     *     
     */
    public void setBlockDeviceMapping(BlockDeviceMapping value) {
        this.blockDeviceMapping = value;
    }

    public boolean isSetBlockDeviceMapping() {
        return (this.blockDeviceMapping!= null);
    }

    /**
     * Sets the value of the ImageId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ImageAttribute withImageId(String value) {
        setImageId(value);
        return this;
    }

    /**
     * Sets the value of the LaunchPermission property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ImageAttribute withLaunchPermission(LaunchPermission value) {
        setLaunchPermission(value);
        return this;
    }

    /**
     * Sets the value of the ProductCode property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public ImageAttribute withProductCode(String... values) {
        for (String value: values) {
            getProductCode().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the KernelId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ImageAttribute withKernelId(String value) {
        setKernelId(value);
        return this;
    }

    /**
     * Sets the value of the RamdiskId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ImageAttribute withRamdiskId(String value) {
        setRamdiskId(value);
        return this;
    }

    /**
     * Sets the value of the BlockDeviceMapping property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ImageAttribute withBlockDeviceMapping(BlockDeviceMapping value) {
        setBlockDeviceMapping(value);
        return this;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param productCode
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(List<String> productCode) {
        this.productCode = productCode;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetImageId()) {
            xml.append("<ImageId>");
            xml.append(escapeXML(getImageId()));
            xml.append("</ImageId>");
        }
        if (isSetLaunchPermission()) {
            LaunchPermission  launchPermission = getLaunchPermission();
            xml.append("<LaunchPermission>");
            xml.append(launchPermission.toXMLFragment());
            xml.append("</LaunchPermission>");
        } 
        java.util.List<String> productCodeList  =  getProductCode();
        for (String productCode : productCodeList) { 
            xml.append("<ProductCode>");
            xml.append(escapeXML(productCode));
            xml.append("</ProductCode>");
        }	
        if (isSetKernelId()) {
            xml.append("<KernelId>");
            xml.append(escapeXML(getKernelId()));
            xml.append("</KernelId>");
        }
        if (isSetRamdiskId()) {
            xml.append("<RamdiskId>");
            xml.append(escapeXML(getRamdiskId()));
            xml.append("</RamdiskId>");
        }
        if (isSetBlockDeviceMapping()) {
            BlockDeviceMapping  blockDeviceMapping = getBlockDeviceMapping();
            xml.append("<BlockDeviceMapping>");
            xml.append(blockDeviceMapping.toXMLFragment());
            xml.append("</BlockDeviceMapping>");
        } 
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetImageId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("ImageId"));
            json.append(" : ");
            json.append(quoteJSON(getImageId()));
            first = false;
        }
        if (isSetLaunchPermission()) {
            if (!first) json.append(", ");
            json.append("\"LaunchPermission\" : {");
            LaunchPermission  launchPermission = getLaunchPermission();


            json.append(launchPermission.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetProductCode()) {
            if (!first) json.append(", ");
            json.append("\"ProductCode\" : [");
            java.util.List<String> productCodeList  =  getProductCode();
            for (String productCode : productCodeList) {
                if (productCodeList.indexOf(productCode) > 0) json.append(", ");
                    json.append(quoteJSON(productCode));
            }
            json.append("]");
            first = false;
        }
        if (isSetKernelId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("KernelId"));
            json.append(" : ");
            json.append(quoteJSON(getKernelId()));
            first = false;
        }
        if (isSetRamdiskId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("RamdiskId"));
            json.append(" : ");
            json.append(quoteJSON(getRamdiskId()));
            first = false;
        }
        if (isSetBlockDeviceMapping()) {
            if (!first) json.append(", ");
            json.append("\"BlockDeviceMapping\" : {");
            BlockDeviceMapping  blockDeviceMapping = getBlockDeviceMapping();


            json.append(blockDeviceMapping.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
