package com.amazonaws.ec2.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KeyPair complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KeyPair">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KeyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KeyFingerprint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KeyMaterial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KeyPair", propOrder = { "keyName", "keyFingerprint", "keyMaterial" })
public class KeyPair {

    @XmlElement(name = "KeyName", required = true)
    protected String keyName;
    @XmlElement(name = "KeyFingerprint", required = true)
    protected String keyFingerprint;
    @XmlElement(name = "KeyMaterial")
    protected String keyMaterial;

    /**
     * Default constructor
     * 
     */
    public KeyPair() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public KeyPair(final String keyName, final String keyFingerprint, final String keyMaterial) {
        this.keyName = keyName;
        this.keyFingerprint = keyFingerprint;
        this.keyMaterial = keyMaterial;
    }

    /**
     * Gets the value of the keyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * Sets the value of the keyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyName(String value) {
        this.keyName = value;
    }

    public boolean isSetKeyName() {
        return (this.keyName != null);
    }

    /**
     * Gets the value of the keyFingerprint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyFingerprint() {
        return keyFingerprint;
    }

    /**
     * Sets the value of the keyFingerprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyFingerprint(String value) {
        this.keyFingerprint = value;
    }

    public boolean isSetKeyFingerprint() {
        return (this.keyFingerprint != null);
    }

    /**
     * Gets the value of the keyMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyMaterial() {
        return keyMaterial;
    }

    /**
     * Sets the value of the keyMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyMaterial(String value) {
        this.keyMaterial = value;
    }

    public boolean isSetKeyMaterial() {
        return (this.keyMaterial != null);
    }

    /**
     * Sets the value of the KeyName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public KeyPair withKeyName(String value) {
        setKeyName(value);
        return this;
    }

    /**
     * Sets the value of the KeyFingerprint property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public KeyPair withKeyFingerprint(String value) {
        setKeyFingerprint(value);
        return this;
    }

    /**
     * Sets the value of the KeyMaterial property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public KeyPair withKeyMaterial(String value) {
        setKeyMaterial(value);
        return this;
    }

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetKeyName()) {
            xml.append("<KeyName>");
            xml.append(escapeXML(getKeyName()));
            xml.append("</KeyName>");
        }
        if (isSetKeyFingerprint()) {
            xml.append("<KeyFingerprint>");
            xml.append(escapeXML(getKeyFingerprint()));
            xml.append("</KeyFingerprint>");
        }
        if (isSetKeyMaterial()) {
            xml.append("<KeyMaterial>");
            xml.append(escapeXML(getKeyMaterial()));
            xml.append("</KeyMaterial>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '&':
                    sb.append("&amp;");
                    break;
                case '<':
                    sb.append("&lt;");
                    break;
                case '>':
                    sb.append("&gt;");
                    break;
                case '\'':
                    sb.append("&#039;");
                    break;
                case '"':
                    sb.append("&quot;");
                    break;
                default:
                    sb.append(c);
            }
        }
        return sb.toString();
    }

    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetKeyName()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("KeyName"));
            json.append(" : ");
            json.append(quoteJSON(getKeyName()));
            first = false;
        }
        if (isSetKeyFingerprint()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("KeyFingerprint"));
            json.append(" : ");
            json.append(quoteJSON(getKeyFingerprint()));
            first = false;
        }
        if (isSetKeyMaterial()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("KeyMaterial"));
            json.append(" : ");
            json.append(quoteJSON(getKeyMaterial()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '/':
                    sb.append("\\/");
                    break;
                case '\b':
                    sb.append("\\b");
                    break;
                case '\f':
                    sb.append("\\f");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < ' ') {
                        sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                    } else {
                        sb.append(c);
                    }
            }
        }
        sb.append("\"");
        return sb.toString();
    }

}
