
package com.amazonaws.ec2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Attribute" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OperationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserGroup" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imageId",
    "attribute",
    "operationType",
    "userId",
    "userGroup",
    "productCode"
})
@XmlRootElement(name = "ModifyImageAttributeRequest")
public class ModifyImageAttributeRequest {

    @XmlElement(name = "ImageId", required = true)
    protected String imageId;
    @XmlElement(name = "Attribute", required = true)
    protected String attribute;
    @XmlElement(name = "OperationType")
    protected String operationType;
    @XmlElement(name = "UserId")
    protected List<String> userId;
    @XmlElement(name = "UserGroup")
    protected List<String> userGroup;
    @XmlElement(name = "ProductCode")
    protected List<String> productCode;

    /**
     * Default constructor
     * 
     */
    public ModifyImageAttributeRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public ModifyImageAttributeRequest(final String imageId, final String attribute, final String operationType, final List<String> userId, final List<String> userGroup, final List<String> productCode) {
        this.imageId = imageId;
        this.attribute = attribute;
        this.operationType = operationType;
        this.userId = userId;
        this.userGroup = userGroup;
        this.productCode = productCode;
    }

    /**
     * Gets the value of the imageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * Sets the value of the imageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageId(String value) {
        this.imageId = value;
    }

    public boolean isSetImageId() {
        return (this.imageId!= null);
    }

    /**
     * Gets the value of the attribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * Sets the value of the attribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttribute(String value) {
        this.attribute = value;
    }

    public boolean isSetAttribute() {
        return (this.attribute!= null);
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

    public boolean isSetOperationType() {
        return (this.operationType!= null);
    }

    /**
     * Gets the value of the userId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUserId() {
        if (userId == null) {
            userId = new ArrayList<String>();
        }
        return this.userId;
    }

    public boolean isSetUserId() {
        return ((this.userId!= null)&&(!this.userId.isEmpty()));
    }

    public void unsetUserId() {
        this.userId = null;
    }

    /**
     * Gets the value of the userGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUserGroup() {
        if (userGroup == null) {
            userGroup = new ArrayList<String>();
        }
        return this.userGroup;
    }

    public boolean isSetUserGroup() {
        return ((this.userGroup!= null)&&(!this.userGroup.isEmpty()));
    }

    public void unsetUserGroup() {
        this.userGroup = null;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProductCode() {
        if (productCode == null) {
            productCode = new ArrayList<String>();
        }
        return this.productCode;
    }

    public boolean isSetProductCode() {
        return ((this.productCode!= null)&&(!this.productCode.isEmpty()));
    }

    public void unsetProductCode() {
        this.productCode = null;
    }

    /**
     * Sets the value of the ImageId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ModifyImageAttributeRequest withImageId(String value) {
        setImageId(value);
        return this;
    }

    /**
     * Sets the value of the Attribute property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ModifyImageAttributeRequest withAttribute(String value) {
        setAttribute(value);
        return this;
    }

    /**
     * Sets the value of the OperationType property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ModifyImageAttributeRequest withOperationType(String value) {
        setOperationType(value);
        return this;
    }

    /**
     * Sets the value of the UserId property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public ModifyImageAttributeRequest withUserId(String... values) {
        for (String value: values) {
            getUserId().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the UserGroup property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public ModifyImageAttributeRequest withUserGroup(String... values) {
        for (String value: values) {
            getUserGroup().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the ProductCode property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public ModifyImageAttributeRequest withProductCode(String... values) {
        for (String value: values) {
            getProductCode().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param userId
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(List<String> userId) {
        this.userId = userId;
    }

    /**
     * Sets the value of the userGroup property.
     * 
     * @param userGroup
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserGroup(List<String> userGroup) {
        this.userGroup = userGroup;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param productCode
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(List<String> productCode) {
        this.productCode = productCode;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetImageId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("ImageId"));
            json.append(" : ");
            json.append(quoteJSON(getImageId()));
            first = false;
        }
        if (isSetAttribute()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Attribute"));
            json.append(" : ");
            json.append(quoteJSON(getAttribute()));
            first = false;
        }
        if (isSetOperationType()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("OperationType"));
            json.append(" : ");
            json.append(quoteJSON(getOperationType()));
            first = false;
        }
        if (isSetUserId()) {
            if (!first) json.append(", ");
            json.append("\"UserId\" : [");
            java.util.List<String> userIdList  =  getUserId();
            for (String userId : userIdList) {
                if (userIdList.indexOf(userId) > 0) json.append(", ");
                    json.append(quoteJSON(userId));
            }
            json.append("]");
            first = false;
        }
        if (isSetUserGroup()) {
            if (!first) json.append(", ");
            json.append("\"UserGroup\" : [");
            java.util.List<String> userGroupList  =  getUserGroup();
            for (String userGroup : userGroupList) {
                if (userGroupList.indexOf(userGroup) > 0) json.append(", ");
                    json.append(quoteJSON(userGroup));
            }
            json.append("]");
            first = false;
        }
        if (isSetProductCode()) {
            if (!first) json.append(", ");
            json.append("\"ProductCode\" : [");
            java.util.List<String> productCodeList  =  getProductCode();
            for (String productCode : productCodeList) {
                if (productCodeList.indexOf(productCode) > 0) json.append(", ");
                    json.append(quoteJSON(productCode));
            }
            json.append("]");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
