package com.amazonaws.ec2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MinCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MaxCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="KeyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecurityGroup" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InstanceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Placement" type="{http://ec2.amazonaws.com/doc/2008-05-05/}Placement" minOccurs="0"/>
 *         &lt;element name="KernelId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RamdiskId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BlockDeviceMapping" type="{http://ec2.amazonaws.com/doc/2008-05-05/}BlockDeviceMapping" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "imageId", "minCount", "maxCount", "keyName", "securityGroup", "userData",
        "instanceType", "placement", "kernelId", "ramdiskId", "blockDeviceMapping" })
@XmlRootElement(name = "RunInstancesRequest")
public class RunInstancesRequest {

    @XmlElement(name = "ImageId", required = true)
    protected String imageId;
    @XmlElement(name = "MinCount")
    protected int minCount;
    @XmlElement(name = "MaxCount")
    protected int maxCount;
    @XmlElement(name = "KeyName")
    protected String keyName;
    @XmlElement(name = "SecurityGroup")
    protected List<String> securityGroup;
    @XmlElement(name = "UserData")
    protected String userData;
    @XmlElement(name = "InstanceType")
    protected String instanceType;
    @XmlElement(name = "Placement")
    protected Placement placement;
    @XmlElement(name = "KernelId")
    protected String kernelId;
    @XmlElement(name = "RamdiskId")
    protected String ramdiskId;
    @XmlElement(name = "BlockDeviceMapping")
    protected List<BlockDeviceMapping> blockDeviceMapping;

    /**
     * Default constructor
     * 
     */
    public RunInstancesRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public RunInstancesRequest(final String imageId, final int minCount, final int maxCount,
            final String keyName, final List<String> securityGroup, final String userData,
            final String instanceType, final Placement placement, final String kernelId,
            final String ramdiskId, final List<BlockDeviceMapping> blockDeviceMapping) {
        this.imageId = imageId;
        this.minCount = minCount;
        this.maxCount = maxCount;
        this.keyName = keyName;
        this.securityGroup = securityGroup;
        this.userData = userData;
        this.instanceType = instanceType;
        this.placement = placement;
        this.kernelId = kernelId;
        this.ramdiskId = ramdiskId;
        this.blockDeviceMapping = blockDeviceMapping;
    }

    /**
     * Gets the value of the imageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * Sets the value of the imageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageId(String value) {
        this.imageId = value;
    }

    public boolean isSetImageId() {
        return (this.imageId != null);
    }

    /**
     * Gets the value of the minCount property.
     * 
     */
    public int getMinCount() {
        return minCount;
    }

    /**
     * Sets the value of the minCount property.
     * 
     */
    public void setMinCount(int value) {
        this.minCount = value;
    }

    public boolean isSetMinCount() {
        return true;
    }

    /**
     * Gets the value of the maxCount property.
     * 
     */
    public int getMaxCount() {
        return maxCount;
    }

    /**
     * Sets the value of the maxCount property.
     * 
     */
    public void setMaxCount(int value) {
        this.maxCount = value;
    }

    public boolean isSetMaxCount() {
        return true;
    }

    /**
     * Gets the value of the keyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * Sets the value of the keyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyName(String value) {
        this.keyName = value;
    }

    public boolean isSetKeyName() {
        return (this.keyName != null);
    }

    /**
     * Gets the value of the securityGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurityGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSecurityGroup() {
        if (securityGroup == null) {
            securityGroup = new ArrayList<String>();
        }
        return this.securityGroup;
    }

    public boolean isSetSecurityGroup() {
        return ((this.securityGroup != null) && (!this.securityGroup.isEmpty()));
    }

    public void unsetSecurityGroup() {
        this.securityGroup = null;
    }

    /**
     * Gets the value of the userData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserData(String value) {
        this.userData = value;
    }

    public boolean isSetUserData() {
        return (this.userData != null);
    }

    /**
     * Gets the value of the instanceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceType() {
        return instanceType;
    }

    /**
     * Sets the value of the instanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceType(String value) {
        this.instanceType = value;
    }

    public boolean isSetInstanceType() {
        return (this.instanceType != null);
    }

    /**
     * Gets the value of the placement property.
     * 
     * @return
     *     possible object is
     *     {@link Placement }
     *     
     */
    public Placement getPlacement() {
        return placement;
    }

    /**
     * Sets the value of the placement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Placement }
     *     
     */
    public void setPlacement(Placement value) {
        this.placement = value;
    }

    public boolean isSetPlacement() {
        return (this.placement != null);
    }

    /**
     * Gets the value of the kernelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKernelId() {
        return kernelId;
    }

    /**
     * Sets the value of the kernelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKernelId(String value) {
        this.kernelId = value;
    }

    public boolean isSetKernelId() {
        return (this.kernelId != null);
    }

    /**
     * Gets the value of the ramdiskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRamdiskId() {
        return ramdiskId;
    }

    /**
     * Sets the value of the ramdiskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRamdiskId(String value) {
        this.ramdiskId = value;
    }

    public boolean isSetRamdiskId() {
        return (this.ramdiskId != null);
    }

    /**
     * Gets the value of the blockDeviceMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blockDeviceMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlockDeviceMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BlockDeviceMapping }
     * 
     * 
     */
    public List<BlockDeviceMapping> getBlockDeviceMapping() {
        if (blockDeviceMapping == null) {
            blockDeviceMapping = new ArrayList<BlockDeviceMapping>();
        }
        return this.blockDeviceMapping;
    }

    public boolean isSetBlockDeviceMapping() {
        return ((this.blockDeviceMapping != null) && (!this.blockDeviceMapping.isEmpty()));
    }

    public void unsetBlockDeviceMapping() {
        this.blockDeviceMapping = null;
    }

    /**
     * Sets the value of the ImageId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunInstancesRequest withImageId(String value) {
        setImageId(value);
        return this;
    }

    /**
     * Sets the value of the MinCount property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunInstancesRequest withMinCount(int value) {
        setMinCount(value);
        return this;
    }

    /**
     * Sets the value of the MaxCount property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunInstancesRequest withMaxCount(int value) {
        setMaxCount(value);
        return this;
    }

    /**
     * Sets the value of the KeyName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunInstancesRequest withKeyName(String value) {
        setKeyName(value);
        return this;
    }

    /**
     * Sets the value of the SecurityGroup property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public RunInstancesRequest withSecurityGroup(String... values) {
        for (String value : values) {
            getSecurityGroup().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the UserData property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunInstancesRequest withUserData(String value) {
        setUserData(value);
        return this;
    }

    /**
     * Sets the value of the InstanceType property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunInstancesRequest withInstanceType(String value) {
        setInstanceType(value);
        return this;
    }

    /**
     * Sets the value of the Placement property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunInstancesRequest withPlacement(Placement value) {
        setPlacement(value);
        return this;
    }

    /**
     * Sets the value of the KernelId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunInstancesRequest withKernelId(String value) {
        setKernelId(value);
        return this;
    }

    /**
     * Sets the value of the RamdiskId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunInstancesRequest withRamdiskId(String value) {
        setRamdiskId(value);
        return this;
    }

    /**
     * Sets the value of the BlockDeviceMapping property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public RunInstancesRequest withBlockDeviceMapping(BlockDeviceMapping... values) {
        for (BlockDeviceMapping value : values) {
            getBlockDeviceMapping().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the securityGroup property.
     * 
     * @param securityGroup
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityGroup(List<String> securityGroup) {
        this.securityGroup = securityGroup;
    }

    /**
     * Sets the value of the blockDeviceMapping property.
     * 
     * @param blockDeviceMapping
     *     allowed object is
     *     {@link BlockDeviceMapping }
     *     
     */
    public void setBlockDeviceMapping(List<BlockDeviceMapping> blockDeviceMapping) {
        this.blockDeviceMapping = blockDeviceMapping;
    }

    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetImageId()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("ImageId"));
            json.append(" : ");
            json.append(quoteJSON(getImageId()));
            first = false;
        }
        if (isSetMinCount()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("MinCount"));
            json.append(" : ");
            json.append(quoteJSON(getMinCount() + ""));
            first = false;
        }
        if (isSetMaxCount()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("MaxCount"));
            json.append(" : ");
            json.append(quoteJSON(getMaxCount() + ""));
            first = false;
        }
        if (isSetKeyName()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("KeyName"));
            json.append(" : ");
            json.append(quoteJSON(getKeyName()));
            first = false;
        }
        if (isSetSecurityGroup()) {
            if (!first)
                json.append(", ");
            json.append("\"SecurityGroup\" : [");
            java.util.List<String> securityGroupList = getSecurityGroup();
            for (String securityGroup : securityGroupList) {
                if (securityGroupList.indexOf(securityGroup) > 0)
                    json.append(", ");
                json.append(quoteJSON(securityGroup));
            }
            json.append("]");
            first = false;
        }
        if (isSetUserData()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("UserData"));
            json.append(" : ");
            json.append(quoteJSON(getUserData()));
            first = false;
        }
        if (isSetInstanceType()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("InstanceType"));
            json.append(" : ");
            json.append(quoteJSON(getInstanceType()));
            first = false;
        }
        if (isSetPlacement()) {
            if (!first)
                json.append(", ");
            json.append("\"Placement\" : {");
            Placement placement = getPlacement();

            json.append(placement.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetKernelId()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("KernelId"));
            json.append(" : ");
            json.append(quoteJSON(getKernelId()));
            first = false;
        }
        if (isSetRamdiskId()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("RamdiskId"));
            json.append(" : ");
            json.append(quoteJSON(getRamdiskId()));
            first = false;
        }
        if (isSetBlockDeviceMapping()) {
            if (!first)
                json.append(", ");
            json.append("\"BlockDeviceMapping\" : [");
            java.util.List<BlockDeviceMapping> blockDeviceMappingList = getBlockDeviceMapping();
            for (BlockDeviceMapping blockDeviceMapping : blockDeviceMappingList) {
                if (blockDeviceMappingList.indexOf(blockDeviceMapping) > 0)
                    json.append(", ");
                json.append("{");
                json.append("");
                json.append(blockDeviceMapping.toJSONFragment());
                json.append("}");
                first = false;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '/':
                    sb.append("\\/");
                    break;
                case '\b':
                    sb.append("\\b");
                    break;
                case '\f':
                    sb.append("\\f");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < ' ') {
                        sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                    } else {
                        sb.append(c);
                    }
            }
        }
        sb.append("\"");
        return sb.toString();
    }

}
