
package com.amazonaws.ec2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RunningInstance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RunningInstance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ImageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InstanceState" type="{http://ec2.amazonaws.com/doc/2008-05-05/}InstanceState"/>
 *         &lt;element name="PrivateDnsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PublicDnsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StateTransitionReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KeyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AmiLaunchIndex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InstanceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LaunchTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Placement" type="{http://ec2.amazonaws.com/doc/2008-05-05/}Placement"/>
 *         &lt;element name="KernelId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RamdiskId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RunningInstance", propOrder = {
    "instanceId",
    "imageId",
    "instanceState",
    "privateDnsName",
    "publicDnsName",
    "stateTransitionReason",
    "keyName",
    "amiLaunchIndex",
    "productCode",
    "instanceType",
    "launchTime",
    "placement",
    "kernelId",
    "ramdiskId"
})
public class RunningInstance {

    @XmlElement(name = "InstanceId", required = true)
    protected String instanceId;
    @XmlElement(name = "ImageId", required = true)
    protected String imageId;
    @XmlElement(name = "InstanceState", required = true)
    protected InstanceState instanceState;
    @XmlElement(name = "PrivateDnsName", required = true)
    protected String privateDnsName;
    @XmlElement(name = "PublicDnsName", required = true)
    protected String publicDnsName;
    @XmlElement(name = "StateTransitionReason")
    protected String stateTransitionReason;
    @XmlElement(name = "KeyName")
    protected String keyName;
    @XmlElement(name = "AmiLaunchIndex")
    protected String amiLaunchIndex;
    @XmlElement(name = "ProductCode")
    protected List<String> productCode;
    @XmlElement(name = "InstanceType", required = true)
    protected String instanceType;
    @XmlElement(name = "LaunchTime", required = true)
    protected String launchTime;
    @XmlElement(name = "Placement", required = true)
    protected Placement placement;
    @XmlElement(name = "KernelId")
    protected String kernelId;
    @XmlElement(name = "RamdiskId")
    protected String ramdiskId;

    /**
     * Default constructor
     * 
     */
    public RunningInstance() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public RunningInstance(final String instanceId, final String imageId, final InstanceState instanceState, final String privateDnsName, final String publicDnsName, final String stateTransitionReason, final String keyName, final String amiLaunchIndex, final List<String> productCode, final String instanceType, final String launchTime, final Placement placement, final String kernelId, final String ramdiskId) {
        this.instanceId = instanceId;
        this.imageId = imageId;
        this.instanceState = instanceState;
        this.privateDnsName = privateDnsName;
        this.publicDnsName = publicDnsName;
        this.stateTransitionReason = stateTransitionReason;
        this.keyName = keyName;
        this.amiLaunchIndex = amiLaunchIndex;
        this.productCode = productCode;
        this.instanceType = instanceType;
        this.launchTime = launchTime;
        this.placement = placement;
        this.kernelId = kernelId;
        this.ramdiskId = ramdiskId;
    }

    /**
     * Gets the value of the instanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * Sets the value of the instanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }

    public boolean isSetInstanceId() {
        return (this.instanceId!= null);
    }

    /**
     * Gets the value of the imageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * Sets the value of the imageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageId(String value) {
        this.imageId = value;
    }

    public boolean isSetImageId() {
        return (this.imageId!= null);
    }

    /**
     * Gets the value of the instanceState property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceState }
     *     
     */
    public InstanceState getInstanceState() {
        return instanceState;
    }

    /**
     * Sets the value of the instanceState property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceState }
     *     
     */
    public void setInstanceState(InstanceState value) {
        this.instanceState = value;
    }

    public boolean isSetInstanceState() {
        return (this.instanceState!= null);
    }

    /**
     * Gets the value of the privateDnsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateDnsName() {
        return privateDnsName;
    }

    /**
     * Sets the value of the privateDnsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateDnsName(String value) {
        this.privateDnsName = value;
    }

    public boolean isSetPrivateDnsName() {
        return (this.privateDnsName!= null);
    }

    /**
     * Gets the value of the publicDnsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicDnsName() {
        return publicDnsName;
    }

    /**
     * Sets the value of the publicDnsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicDnsName(String value) {
        this.publicDnsName = value;
    }

    public boolean isSetPublicDnsName() {
        return (this.publicDnsName!= null);
    }

    /**
     * Gets the value of the stateTransitionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateTransitionReason() {
        return stateTransitionReason;
    }

    /**
     * Sets the value of the stateTransitionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateTransitionReason(String value) {
        this.stateTransitionReason = value;
    }

    public boolean isSetStateTransitionReason() {
        return (this.stateTransitionReason!= null);
    }

    /**
     * Gets the value of the keyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * Sets the value of the keyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyName(String value) {
        this.keyName = value;
    }

    public boolean isSetKeyName() {
        return (this.keyName!= null);
    }

    /**
     * Gets the value of the amiLaunchIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmiLaunchIndex() {
        return amiLaunchIndex;
    }

    /**
     * Sets the value of the amiLaunchIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmiLaunchIndex(String value) {
        this.amiLaunchIndex = value;
    }

    public boolean isSetAmiLaunchIndex() {
        return (this.amiLaunchIndex!= null);
    }

    /**
     * Gets the value of the productCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProductCode() {
        if (productCode == null) {
            productCode = new ArrayList<String>();
        }
        return this.productCode;
    }

    public boolean isSetProductCode() {
        return ((this.productCode!= null)&&(!this.productCode.isEmpty()));
    }

    public void unsetProductCode() {
        this.productCode = null;
    }

    /**
     * Gets the value of the instanceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceType() {
        return instanceType;
    }

    /**
     * Sets the value of the instanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceType(String value) {
        this.instanceType = value;
    }

    public boolean isSetInstanceType() {
        return (this.instanceType!= null);
    }

    /**
     * Gets the value of the launchTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaunchTime() {
        return launchTime;
    }

    /**
     * Sets the value of the launchTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaunchTime(String value) {
        this.launchTime = value;
    }

    public boolean isSetLaunchTime() {
        return (this.launchTime!= null);
    }

    /**
     * Gets the value of the placement property.
     * 
     * @return
     *     possible object is
     *     {@link Placement }
     *     
     */
    public Placement getPlacement() {
        return placement;
    }

    /**
     * Sets the value of the placement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Placement }
     *     
     */
    public void setPlacement(Placement value) {
        this.placement = value;
    }

    public boolean isSetPlacement() {
        return (this.placement!= null);
    }

    /**
     * Gets the value of the kernelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKernelId() {
        return kernelId;
    }

    /**
     * Sets the value of the kernelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKernelId(String value) {
        this.kernelId = value;
    }

    public boolean isSetKernelId() {
        return (this.kernelId!= null);
    }

    /**
     * Gets the value of the ramdiskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRamdiskId() {
        return ramdiskId;
    }

    /**
     * Sets the value of the ramdiskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRamdiskId(String value) {
        this.ramdiskId = value;
    }

    public boolean isSetRamdiskId() {
        return (this.ramdiskId!= null);
    }

    /**
     * Sets the value of the InstanceId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withInstanceId(String value) {
        setInstanceId(value);
        return this;
    }

    /**
     * Sets the value of the ImageId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withImageId(String value) {
        setImageId(value);
        return this;
    }

    /**
     * Sets the value of the InstanceState property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withInstanceState(InstanceState value) {
        setInstanceState(value);
        return this;
    }

    /**
     * Sets the value of the PrivateDnsName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withPrivateDnsName(String value) {
        setPrivateDnsName(value);
        return this;
    }

    /**
     * Sets the value of the PublicDnsName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withPublicDnsName(String value) {
        setPublicDnsName(value);
        return this;
    }

    /**
     * Sets the value of the StateTransitionReason property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withStateTransitionReason(String value) {
        setStateTransitionReason(value);
        return this;
    }

    /**
     * Sets the value of the KeyName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withKeyName(String value) {
        setKeyName(value);
        return this;
    }

    /**
     * Sets the value of the AmiLaunchIndex property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withAmiLaunchIndex(String value) {
        setAmiLaunchIndex(value);
        return this;
    }

    /**
     * Sets the value of the ProductCode property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public RunningInstance withProductCode(String... values) {
        for (String value: values) {
            getProductCode().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the InstanceType property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withInstanceType(String value) {
        setInstanceType(value);
        return this;
    }

    /**
     * Sets the value of the LaunchTime property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withLaunchTime(String value) {
        setLaunchTime(value);
        return this;
    }

    /**
     * Sets the value of the Placement property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withPlacement(Placement value) {
        setPlacement(value);
        return this;
    }

    /**
     * Sets the value of the KernelId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withKernelId(String value) {
        setKernelId(value);
        return this;
    }

    /**
     * Sets the value of the RamdiskId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunningInstance withRamdiskId(String value) {
        setRamdiskId(value);
        return this;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param productCode
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(List<String> productCode) {
        this.productCode = productCode;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetInstanceId()) {
            xml.append("<InstanceId>");
            xml.append(escapeXML(getInstanceId()));
            xml.append("</InstanceId>");
        }
        if (isSetImageId()) {
            xml.append("<ImageId>");
            xml.append(escapeXML(getImageId()));
            xml.append("</ImageId>");
        }
        if (isSetInstanceState()) {
            InstanceState  instanceState = getInstanceState();
            xml.append("<InstanceState>");
            xml.append(instanceState.toXMLFragment());
            xml.append("</InstanceState>");
        } 
        if (isSetPrivateDnsName()) {
            xml.append("<PrivateDnsName>");
            xml.append(escapeXML(getPrivateDnsName()));
            xml.append("</PrivateDnsName>");
        }
        if (isSetPublicDnsName()) {
            xml.append("<PublicDnsName>");
            xml.append(escapeXML(getPublicDnsName()));
            xml.append("</PublicDnsName>");
        }
        if (isSetStateTransitionReason()) {
            xml.append("<StateTransitionReason>");
            xml.append(escapeXML(getStateTransitionReason()));
            xml.append("</StateTransitionReason>");
        }
        if (isSetKeyName()) {
            xml.append("<KeyName>");
            xml.append(escapeXML(getKeyName()));
            xml.append("</KeyName>");
        }
        if (isSetAmiLaunchIndex()) {
            xml.append("<AmiLaunchIndex>");
            xml.append(escapeXML(getAmiLaunchIndex()));
            xml.append("</AmiLaunchIndex>");
        }
        java.util.List<String> productCodeList  =  getProductCode();
        for (String productCode : productCodeList) { 
            xml.append("<ProductCode>");
            xml.append(escapeXML(productCode));
            xml.append("</ProductCode>");
        }	
        if (isSetInstanceType()) {
            xml.append("<InstanceType>");
            xml.append(escapeXML(getInstanceType()));
            xml.append("</InstanceType>");
        }
        if (isSetLaunchTime()) {
            xml.append("<LaunchTime>");
            xml.append(escapeXML(getLaunchTime()));
            xml.append("</LaunchTime>");
        }
        if (isSetPlacement()) {
            Placement  placement = getPlacement();
            xml.append("<Placement>");
            xml.append(placement.toXMLFragment());
            xml.append("</Placement>");
        } 
        if (isSetKernelId()) {
            xml.append("<KernelId>");
            xml.append(escapeXML(getKernelId()));
            xml.append("</KernelId>");
        }
        if (isSetRamdiskId()) {
            xml.append("<RamdiskId>");
            xml.append(escapeXML(getRamdiskId()));
            xml.append("</RamdiskId>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetInstanceId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("InstanceId"));
            json.append(" : ");
            json.append(quoteJSON(getInstanceId()));
            first = false;
        }
        if (isSetImageId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("ImageId"));
            json.append(" : ");
            json.append(quoteJSON(getImageId()));
            first = false;
        }
        if (isSetInstanceState()) {
            if (!first) json.append(", ");
            json.append("\"InstanceState\" : {");
            InstanceState  instanceState = getInstanceState();


            json.append(instanceState.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetPrivateDnsName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("PrivateDnsName"));
            json.append(" : ");
            json.append(quoteJSON(getPrivateDnsName()));
            first = false;
        }
        if (isSetPublicDnsName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("PublicDnsName"));
            json.append(" : ");
            json.append(quoteJSON(getPublicDnsName()));
            first = false;
        }
        if (isSetStateTransitionReason()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("StateTransitionReason"));
            json.append(" : ");
            json.append(quoteJSON(getStateTransitionReason()));
            first = false;
        }
        if (isSetKeyName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("KeyName"));
            json.append(" : ");
            json.append(quoteJSON(getKeyName()));
            first = false;
        }
        if (isSetAmiLaunchIndex()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("AmiLaunchIndex"));
            json.append(" : ");
            json.append(quoteJSON(getAmiLaunchIndex()));
            first = false;
        }
        if (isSetProductCode()) {
            if (!first) json.append(", ");
            json.append("\"ProductCode\" : [");
            java.util.List<String> productCodeList  =  getProductCode();
            for (String productCode : productCodeList) {
                if (productCodeList.indexOf(productCode) > 0) json.append(", ");
                    json.append(quoteJSON(productCode));
            }
            json.append("]");
            first = false;
        }
        if (isSetInstanceType()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("InstanceType"));
            json.append(" : ");
            json.append(quoteJSON(getInstanceType()));
            first = false;
        }
        if (isSetLaunchTime()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("LaunchTime"));
            json.append(" : ");
            json.append(quoteJSON(getLaunchTime()));
            first = false;
        }
        if (isSetPlacement()) {
            if (!first) json.append(", ");
            json.append("\"Placement\" : {");
            Placement  placement = getPlacement();


            json.append(placement.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetKernelId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("KernelId"));
            json.append(" : ");
            json.append(quoteJSON(getKernelId()));
            first = false;
        }
        if (isSetRamdiskId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("RamdiskId"));
            json.append(" : ");
            json.append(quoteJSON(getRamdiskId()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
