package com.amazonaws.ec2.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecurityGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OwnerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GroupDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IpPermission" type="{http://ec2.amazonaws.com/doc/2008-05-05/}IpPermission" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Thu Aug 28 20:50:29 PDT 2008
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityGroup", propOrder = { "ownerId", "groupName", "groupDescription", "ipPermission" })
public class SecurityGroup {

    @XmlElement(name = "OwnerId", required = true)
    protected String ownerId;
    @XmlElement(name = "GroupName", required = true)
    protected String groupName;
    @XmlElement(name = "GroupDescription", required = true)
    protected String groupDescription;
    @XmlElement(name = "IpPermission", required = true)
    protected List<IpPermission> ipPermission;

    /**
     * Default constructor
     * 
     */
    public SecurityGroup() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public SecurityGroup(final String ownerId, final String groupName, final String groupDescription,
            final List<IpPermission> ipPermission) {
        this.ownerId = ownerId;
        this.groupName = groupName;
        this.groupDescription = groupDescription;
        this.ipPermission = ipPermission;
    }

    /**
     * Gets the value of the ownerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerId(String value) {
        this.ownerId = value;
    }

    public boolean isSetOwnerId() {
        return (this.ownerId != null);
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    public boolean isSetGroupName() {
        return (this.groupName != null);
    }

    /**
     * Gets the value of the groupDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupDescription() {
        return groupDescription;
    }

    /**
     * Sets the value of the groupDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupDescription(String value) {
        this.groupDescription = value;
    }

    public boolean isSetGroupDescription() {
        return (this.groupDescription != null);
    }

    /**
     * Gets the value of the ipPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IpPermission }
     * 
     * 
     */
    public List<IpPermission> getIpPermission() {
        if (ipPermission == null) {
            ipPermission = new ArrayList<IpPermission>();
        }
        return this.ipPermission;
    }

    public boolean isSetIpPermission() {
        return ((this.ipPermission != null) && (!this.ipPermission.isEmpty()));
    }

    public void unsetIpPermission() {
        this.ipPermission = null;
    }

    /**
     * Sets the value of the OwnerId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public SecurityGroup withOwnerId(String value) {
        setOwnerId(value);
        return this;
    }

    /**
     * Sets the value of the GroupName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public SecurityGroup withGroupName(String value) {
        setGroupName(value);
        return this;
    }

    /**
     * Sets the value of the GroupDescription property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public SecurityGroup withGroupDescription(String value) {
        setGroupDescription(value);
        return this;
    }

    /**
     * Sets the value of the IpPermission property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public SecurityGroup withIpPermission(IpPermission... values) {
        for (IpPermission value : values) {
            getIpPermission().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the ipPermission property.
     * 
     * @param ipPermission
     *     allowed object is
     *     {@link IpPermission }
     *     
     */
    public void setIpPermission(List<IpPermission> ipPermission) {
        this.ipPermission = ipPermission;
    }

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetOwnerId()) {
            xml.append("<OwnerId>");
            xml.append(escapeXML(getOwnerId()));
            xml.append("</OwnerId>");
        }
        if (isSetGroupName()) {
            xml.append("<GroupName>");
            xml.append(escapeXML(getGroupName()));
            xml.append("</GroupName>");
        }
        if (isSetGroupDescription()) {
            xml.append("<GroupDescription>");
            xml.append(escapeXML(getGroupDescription()));
            xml.append("</GroupDescription>");
        }
        java.util.List<IpPermission> ipPermissionList = getIpPermission();
        for (IpPermission ipPermission : ipPermissionList) {
            xml.append("<IpPermission>");
            xml.append(ipPermission.toXMLFragment());
            xml.append("</IpPermission>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '&':
                    sb.append("&amp;");
                    break;
                case '<':
                    sb.append("&lt;");
                    break;
                case '>':
                    sb.append("&gt;");
                    break;
                case '\'':
                    sb.append("&#039;");
                    break;
                case '"':
                    sb.append("&quot;");
                    break;
                default:
                    sb.append(c);
            }
        }
        return sb.toString();
    }

    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetOwnerId()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("OwnerId"));
            json.append(" : ");
            json.append(quoteJSON(getOwnerId()));
            first = false;
        }
        if (isSetGroupName()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("GroupName"));
            json.append(" : ");
            json.append(quoteJSON(getGroupName()));
            first = false;
        }
        if (isSetGroupDescription()) {
            if (!first)
                json.append(", ");
            json.append(quoteJSON("GroupDescription"));
            json.append(" : ");
            json.append(quoteJSON(getGroupDescription()));
            first = false;
        }
        if (isSetIpPermission()) {
            if (!first)
                json.append(", ");
            json.append("\"IpPermission\" : [");
            java.util.List<IpPermission> ipPermissionList = getIpPermission();
            for (IpPermission ipPermission : ipPermissionList) {
                if (ipPermissionList.indexOf(ipPermission) > 0)
                    json.append(", ");
                json.append("{");
                json.append("");
                json.append(ipPermission.toJSONFragment());
                json.append("}");
                first = false;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '/':
                    sb.append("\\/");
                    break;
                case '\b':
                    sb.append("\\b");
                    break;
                case '\f':
                    sb.append("\\f");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < ' ') {
                        sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                    } else {
                        sb.append(c);
                    }
            }
        }
        sb.append("\"");
        return sb.toString();
    }

}
