package org.objectweb.proactive.ic2d.jmxmonitoring.ic3d.menu;

public enum MenuAction {
	HOST_REFRESH,
	HOST_STOP_MONITORING,
	HOST_CHARTIT,
	RUNTIME_KILL,
	RUNTIME_REFRESH,
	RUNTIME_STOP_MONITORING,
	RUNTIME_CHARTIT,
	NODE_STOP_MONITORING,
	NODE_REFRESH,
	NODE_CHARTIT,
	AO_STOPMONITORING
};
